version: '3.8'

services:
  app:
    image: debian:bullseye-slim
    command: sleep infinity
    environment:
      RUSTUP_TOOLCHAIN: nightly
    hostname: rustysub
    networks:
      - rustysubnet
    volumes:
      - ../..:/workspaces:cached
 
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: rusty
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    hostname: pgrusty
    networks:
      - rustysubnet
    restart: unless-stopped
    volumes:
      - pg-rusty-data:/var/lib/postgresql/data

volumes:
  pg-rusty-data:

networks:
  rustysubnet:
